### ISSUE TITLE
minio server segmentation fault in docker

### ISSUE THREAD

**Issue by ZegWe** [syzoj/syzoj-ng#22]
I met segmentation fault when set up MinIO Server in centos docker
<img width="574" alt="スクリーンショット 2020-09-30 1 02 24" src="https://user-images.githubusercontent.com/22636524/94590136-d07ca600-02b8-11eb-88a8-e28ac1cc6eaa.png">

**Comment by Menci** [comment]
1. No ancient operating system please
2. Stack trace
3. File the issue to https://github.com/minio/minio

**Comment by masnn** [comment]
Suggestion: specific linux core version in README (e.g. Linux 4.4+)
